core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

creator/urls.py
# from django.contrib.auth import views as auth_views
# from django.urls import path
# from . import api
# from . import views

# app_name = 'creator'

# urlpatterns = [
#     path('api/create_support', api.create_support, name='api_create_support'),
#     path('mypage/', views.mypage, name="mypage"),
#     path('creators/', views.creators, name='creators'),
#     path('creators/<int:pk>', views.creator, name='creator'),
#     path('creators/<int:creator_id>/success/<int:support_id>', views.support_success, name='success'),
#     path('edit/', views.edit, name='edit'),
#     path('signup/', views.signup, name='signup'),
#     path('login/', auth_views.LoginView.as_view(template_name='creator/login.html'), name='login'),
# ]


# from django.urls import path
# from . import views, api

# urlpatterns = [
#     path('reload-card/', views.reload_card_view, name='reload_card'),
#     path('purchase-ticket/', views.purchase_ticket_view, name='purchase_ticket'),
#     path('api/reload-card/', api.reload_card, name='api_reload_card'),
#     path('api/purchase-ticket/', api.purchase_ticket, name='api_purchase_ticket'),
#     path('api/bitcoin-payment/', api.bitcoin_payment, name='api_bitcoin_payment'),
# ]


from django.contrib.auth import views as auth_views
from django.urls import path
from . import api
from . import views

app_name = 'creator'

urlpatterns = [
    #sample
    path('create/', views.passenger_form, name="passenger_insert"),
    path('list/', views.passenger_list, name="passenger_list"),
    path('<int:id>/', views.passenger_form, name="passenger_update"),
    path('delete/<int:id>', views.passenger_delete, name="passenger_delete"),
    
    path('createReg/', views.reg_passenger_form, name="reg_passenger_insert"),
    path('listReg/', views.reg_passenger_list, name="reg_passenger_list"),
    path('<int:id>/', views.reg_passenger_form, name="reg_passenger_update"),
    path('deleteReg/<int:id>', views.passenger_delete, name="reg_passenger_delete"),
    # Existing paths
    path('api/create_support', api.create_support, name='api_create_support'),
    path('mypage/', views.mypage, name="mypage"),
    path('mypage/', views.creators, name='creators'),
    path('creators/<int:pk>', views.creator, name='creator'),
    path('creators/<int:creator_id>/success/<int:support_id>', views.support_success, name='success'),
    path('edit/', views.edit, name='edit'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='creator/login.html'), name='login'),
    # Change `bitcoin/` to `bitcoin_transactions/`
    path('bitcoin_transactions/', views.bitcoin_transactions, name='bitcoin_transactions'),
    path('api/create_bitcoin_transaction/', views.create_bitcoin_transaction, name='create_bitcoin_transaction'),
    path('api/cryptomus_callback/', views.cryptomus_callback, name='cryptomus_callback'),
]

gateway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('passenger/',include('creator.urls')),
    path('', include('core.urls')),
    path('', include('creator.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect
from creator.models import Creator

def index(request):
    creators = Creator.objects.all()
    
    if request.user.is_authenticated:
        try:
            creator = request.user.creator
        except Exception:
            return redirect('creator:edit')
        
    return render(request, 'core/index.html', {
        'creators': creators
    })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title %}{% endblock %} | Tap your NFC card</title>
      </head>
      
      <body class="bg-slate-700">
        <nav class="py-8 px-8 flex flex-row items-center justify-between bg-slate-900">
          <div>
            <a href="{% url 'core:index' %}" class="text-2xl text-white font-bold">Tap your NFC card</a>
          </div>
      
          <div class="space-x-6">
            <a href="{%url 'creator:creators'%}" class="py-4 px-6 text-lg font-bold text-white">Creators</a>

            {%if not request.user.is_authenticated%}

            <a href="{%url 'creator:login'%}" class="py-4 px-6 text-lg font-bold text-white">Log in</a>
            <a href="{%url 'creator:signup'%}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">Sign up</a>
         
            {% endif %}

            {%if request.user.is_authenticated%}
            <a href="{%url 'creator:mypage'%}" class="py-4 px-6 text-lg font-bold text-white bg-sky-800 rounded-lg">My page</a>
            {%endif%}
         
          </div>
        </nav>

        <main class="py-6 px-8">

          {%block content%}
          {%endblock%}
          
          </main>

          <footer class="py-6 px-8 text-center bg-slate-600">
            <p class="text-slate-200">Copyright (c) 2024 – Buy me a noodle</p>
        </footer>        
        {%block scripts%}
        {%endblock%}  

      </body>
      

</html>

core/templates/core/index.html
 {% extends "core/base.html" %}

 {% load static %}

 {% block title %}Welcome{% endblock %}

 {%block content%}

 <div class="py-20 text-center space-y-12">
    <h1 class="text-7xl text-slate-300 font-bold">Get paid for your work</h1>
    <p class="text-xl text-slate-400">
      This is just some random information to show how it would look like with some actual text.
    </p>
    <a href="{%url 'creator:signup'%}" class="py-8 px-12 inline-block text-xl text-white bg-sky-800 rounded-lg">Read more</a>
  </div>

  <div class="py-12 bg-slate-800">
    <h2 class="mb-12 text-5xl text-slate-300 text-center font-bold">
      Newest creators
    </h2>

    <div class="px-12 grid grid-cols-4 gap-8">
      {%for creator in creators%}

     <div class="bg-slate-600 rounded-lg">
       <figure>
         <img src="{{creator.image.url}}" alt="" class="rounded-tr-lg rounded-tl-lg">
       </figure>

       <div class="py-6 px-8 space-y-6">
         <h3 class="text-xl text-slate-200 font-bold">{{creator.title}}</h3>
         <p class="text-slate-300">
            {{creator.description}}
         </p>
         <a href="{%url 'creator:creator' creator.pk%}" class="py-4 px-6 inline-block text-xl text-white bg-sky-800 rounded-xl">Read more</a>

       </div>
     </div>
     {%endfor%}
    </div>
  </div>

  {%endblock%}